### ISSUE TITLE
cron/help error

### ISSUE THREAD

**Issue by DrDeath72** [DenisOgr/yii2-cronjobs#10]
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: denisog\cronjobs\CronController::getName()'
in /.../vendor/yiisoft/yii2/base/Component.php:285

Stack trace:
#0 /.../vendor/denisogr/yii2-cronjobs/CronController.php(91): yii\base\Component->__call('getName', Array)
#1 /.../vendor/denisogr/yii2-cronjobs/CronController.php(91): denisog\cronjobs\CronController->getName()
#2 /.../vendor/denisogr/yii2-cronjobs/CronController.php(292): denisog\cronjobs\CronController->getHelp()
#3 [internal function]: denisog\cronjobs\CronController->actionHelp()

**Comment by kafeg** [comment]
I will fix it, see https://github.com/DenisOgr/yii2-cronjobs/pull/12
