### ISSUE TITLE
Exception 'ReflectionException'

### ISSUE THREAD

**Issue by ghost** [DenisOgr/yii2-cronjobs#9]
Hi,

When I tried to execute ./yii cron it returns the next error:

Exception 'ReflectionException' with message 'Class denisog\cronjobs\CronController does not exist'

in /home/proyect/public_html/vendor/yiisoft/yii2/di/Container.php:415

Stack trace:
#0 /home/proyect/public_html/vendor/yiisoft/yii2/di/Container.php(415): ReflectionClass->__construct('denisog\cronjob...')
#1 /home/proyect/public_html/vendor/yiisoft/yii2/di/Container.php(358): yii\di\Container->getDependencies('denisog\cronjob...')
#2 /home/proyect/public_html/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('denisog\cronjob...', Array, Array)
#3 /home/proyect/public_html/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('denisog\cronjob...', Array, Array)
#4 /home/proyect/public_html/vendor/yiisoft/yii2/base/Module.php(508): yii\BaseYii::createObject(Array, Array)
#5 /home/proyect/public_html/vendor/yiisoft/yii2/base/Module.php(449): yii\base\Module->createController('cron')
#6 /home/proyect/public_html/vendor/yiisoft/yii2/console/Application.php(161): yii\base\Module->runAction('cron', Array)
#7 /home/proyect/public_html/vendor/yiisoft/yii2/console/Application.php(137): yii\console\Application->runAction('cron', Array)
#8 /home/proyect/public_html/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /home/proyect/public_html/yii(31): yii\base\Application->run()
#10 {main}

I'm using advanced template, with this configuration:
# config / main

Added:

``` php
'controllerMap' => [
        'cron' => [
           'class' => 'denisog\cronjobs\CronController',
        ],
    ],
```
# config / params-local

``` php
return [
    'cronJobs' => [
        'test/index' => [
            'cron' => '0 * * * *', // Every hour
        ],
    ],
];
```

And my test controller:

``` php
namespace console\controllers;
use yii\console\Controller;

class TestController extends Controller {

    public function actionIndex() {
        echo "cron service running\n";
    }
}
```

In localhost works fine, but in testing breaks. In both,  ./yii test works well too.

Thanks in advance

**Comment by Lynnworld** [comment]
make sure you have yii2-cronjobs in /vendor by composer 。
